name: Run Newman Tests

on:
  push:
    branches:
      - main

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman
      run: newman run Api Session.postman_collection.json

    - name: Upload Newman Report
      uses: actions/upload-artifact@v2
      with:
        name: newman-report
        path: newman/*.json 

