name: Demo ci cid pipline

on:
  push:
    branches:
      - main
  schedule: 
    - cron: '0 16 * * *'
jobs: 
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          continue-on-error: true
      - name: Set up maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn clean install
      - name: Run Test
        run: mvn test "-Dcucumber.filter.tags=@validation"
        env:
          DISPLAY: 19
          CUCUMBER_PUBLISH_TOKEN: fw3232343234
    
